name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit semgrep
        
    - name: Run Safety (dependency vulnerability scan)
      run: |
        echo "Running dependency vulnerability scan..."
        safety check --json --output safety-report.json || echo "Safety scan completed with warnings"
        safety check || echo "Safety check completed with warnings"
        
    - name: Run Bandit (security linting)
      run: |
        echo "Running security linting..."
        bandit -r . -f json -o bandit-report.json || echo "Bandit scan completed with warnings"
        bandit -r . -ll || echo "Bandit linting completed with warnings"
        
    - name: Run Semgrep (static analysis)
      run: |
        echo "Running static analysis..."
        semgrep --config=auto --json --output=semgrep-report.json . || echo "Semgrep scan completed with warnings"
        semgrep --config=auto . || echo "Semgrep analysis completed with warnings"
        
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
          semgrep-report.json
          
    - name: Comment PR with security results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          let comment = '## 🔒 Security Scan Results\n\n';
          
          // Check if reports exist and add results
          if (fs.existsSync('safety-report.json')) {
            comment += '### Dependencies: ✅ Scanned\n';
          }
          if (fs.existsSync('bandit-report.json')) {
            comment += '### Code Security: ✅ Scanned\n';
          }
          if (fs.existsSync('semgrep-report.json')) {
            comment += '### Static Analysis: ✅ Scanned\n';
          }
          
          comment += '\n📋 Detailed reports available in workflow artifacts.';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
